# Generated by Django 4.1.4 on 2022-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transacao_options_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
