# Generated by Django 4.1.4 on 2022-12-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
