# Generated by Django 4.1.4 on 2022-12-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_rename_categoria_transacao_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={},
        ),
    ]
