# Generated by Django 4.1.4 on 2022-12-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_alter_transacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name_plural': 'Transações'},
        ),
    ]
